#!/usr/bin/env node
// lifecycle/aggregate-week.js — WEEKLY brief generator.
//
// Reads the last 7 days of `runs`, rolls them into a week summary, computes
// deltas vs the prior week, derives deterministic config-change proposals,
// writes a markdown BRIEF to ~/.pi/agent/proposals/<date>.md, and inserts a
// `proposals` row (status='proposed'). Does NOT apply anything — the user
// reviews with `apple-pi review` and applies with `apple-pi apply`.
//
// Pure local Node, no LLM (L2). Safe to run unattended.
//
// Usage:
//   node --no-warnings lifecycle/aggregate-week.js          # week ending today
//   node --no-warnings lifecycle/aggregate-week.js --dry    # print brief, persist nothing
//   node --no-warnings lifecycle/aggregate-week.js --end 2026-06-27

"use strict";
const { writeFileSync, mkdirSync } = require("node:fs");
const { open, todayLocal, isoNow, piDir } = require("./lib/db");
const { rollWeek, deriveProposals } = require("./lib/brief");

function parseArgs(argv) {
	const out = { end: null, dry: false };
	for (let i = 2; i < argv.length; i++) {
		if (argv[i] === "--dry") out.dry = true;
		else if (argv[i] === "--end") out.end = argv[++i];
		else { console.error(`unknown arg: ${argv[i]}`); process.exit(2); }
	}
	return out;
}

function readSettings() {
	const p = `${piDir()}/agent/settings.json`;
	try { return JSON.parse(require("node:fs").readFileSync(p, "utf8")); }
	catch { return {}; }
}

// Build the brief markdown. curr/prev are rolled weeks (or prev=null).
function renderBrief({ weekStart, weekEnd, curr, prev, proposals }) {
	const Δ = (c, p, key) => (prev ? c - p : null);
	const fmtΔ = (v) => (v === null ? "—" : (v >= 0 ? `+${v}` : `${v}`));
	const topTools = Object.entries(curr.tools).sort((a, b) => b[1] - a[1]).slice(0, 6);
	const topModels = Object.entries(curr.models).sort((a, b) => b[1] - a[1]);
	const lines = [];
	lines.push(`# apple-pi weekly self-improvement brief`);
	lines.push(``);
	lines.push(`**Week:** ${weekStart} → ${weekEnd}  ·  **generated:** ${isoNow()}`);
	lines.push(``);
	lines.push(`> Review the proposed changes below. To apply: \`apple-pi apply --latest\`.`);
	lines.push(`> To reject: \`apple-pi reject --latest\`. Nothing changes until you apply.`);
	lines.push(``);
	lines.push(`## This week at a glance`);
	lines.push(``);
	lines.push(`| metric | this week | last week | Δ |`);
	lines.push(`|---|---:|---:|---:|`);
	lines.push(`| days with data | ${curr.days} | ${prev ? prev.days : "—"} | ${fmtΔ(curr.days - (prev ? prev.days : 0))} |`);
	lines.push(`| sessions | ${curr.sessions} | ${prev ? prev.sessions : "—"} | ${fmtΔ(Δ(curr.sessions, prev && prev.sessions, 0) || 0)} |`);
	lines.push(`| turns | ${curr.turns} | ${prev ? prev.turns : "—"} | ${fmtΔ(Δ(curr.turns, prev && prev.turns, 0) || 0)} |`);
	lines.push(`| tool calls | ${Object.values(curr.tools).reduce((a, b) => a + b, 0)} | ${prev ? Object.values(prev.tools).reduce((a, b) => a + b, 0) : "—"} | — |`);
	lines.push(`| tokens in (M) | ${(curr.tokensIn / 1e6).toFixed(2)} | ${prev ? (prev.tokensIn / 1e6).toFixed(2) : "—"} | — |`);
	lines.push(`| tokens out (M) | ${(curr.tokensOut / 1e6).toFixed(2)} | ${prev ? (prev.tokensOut / 1e6).toFixed(2) : "—"} | — |`);
	lines.push(`| tool errors | ${curr.errors} | ${prev ? prev.errors : "—"} | ${fmtΔ(Δ(curr.errors, prev && prev.errors, 0) || 0)} |`);
	lines.push(`| cost ($) | ${curr.cost.toFixed(4)} | ${prev ? prev.cost.toFixed(4) : "—"} | — |`);
	lines.push(``);
	lines.push(`**Tool mix:** bash ${curr.bashPct}% · read-like (read/grep/find/ls) ${curr.readPct}%`);
	lines.push(``);
	lines.push(`**Top tools:** ${topTools.map(([k, v]) => `${k}(${v})`).join(", ") || "—"}`);
	lines.push(``);
	lines.push(`**Models:** ${topModels.map(([k, v]) => `${k}(${v} turns)`).join(", ") || "—"}`);
	lines.push(``);
	lines.push(`## Proposed changes (${proposals.length})`);
	lines.push(``);
	if (proposals.length === 0) {
		lines.push(`No config changes proposed this week. The config looks healthy against this week's usage.`);
	} else {
		// Group by source so the brief is explicit about what's behavioral
		// (autoresearch, from your telemetry) vs what's a code update (release).
		const bySource = {};
		for (const p of proposals) {
			const s = p.source || "autoresearch";
			(bySource[s] = bySource[s] || []).push(p);
		}
		const labels = {
			autoresearch: "Self-improvement (from your session telemetry) — review + apply",
			release: "Release updates (new code from GitHub) — never auto-applied; run the command",
		};
		for (const s of Object.keys(bySource)) {
			lines.push(`### source: ${s} — ${labels[s] || s}`);
			lines.push(``);
			for (const p of bySource[s]) {
				lines.push(`- **[${p.severity}]** \`${p.setting}\`: \`${p.from}\` → \`${p.to}\``);
				lines.push(`  - ${p.rationale}`);
			}
			lines.push(``);
		}
	}
	lines.push(`---`);
	lines.push(`*Generated by apple-pi aggregate-week. Apply self-improvement proposals with \`apple-pi apply --latest\`. Release updates need \`apple-pi update --all --yes\`.*`);
	return lines.join("\n");
}

function main() {
	const args = parseArgs(process.argv);
	const end = args.end || todayLocal();
	const db = open("ro");

	// Week = [end-6, end]. Prior week = [end-13, end-7].
	const dayMs = 86400000;
	const endD = new Date(end + "T00:00:00");
	const iso = (offset) => todayLocal(new Date(endD.getTime() + offset * dayMs));
	const weekDates = []; for (let i = 6; i >= 0; i--) weekDates.push(iso(-i));
	const prevDates = []; for (let i = 13; i >= 7; i--) prevDates.push(iso(-i));

	const qMarks = (n) => Array(n).fill("?").join(",");
	const currRows = db.prepare(`SELECT * FROM runs WHERE run_date IN (${qMarks(weekDates.length)})`).all(...weekDates);
	const prevRows = db.prepare(`SELECT * FROM runs WHERE run_date IN (${qMarks(prevDates.length)})`).all(...prevDates);

	if (currRows.length === 0) {
		console.log(`aggregate-week: no runs data for ${weekDates[0]}..${weekDates[6]}. Run collect-metrics first.`);
		db.close(); return;
	}

	const curr = rollWeek(currRows);
	const prev = prevRows.length ? rollWeek(prevRows) : null;
	const settings = readSettings();
	const proposals = deriveProposals(curr, prev, settings);

	// Fold in a read-only release check: each behind-repo becomes a
	// source:'release' proposal so the brief is explicit about code updates
	// vs behavioral self-improvement. Never auto-applied.
	try {
		const { checkAll } = require("./update-check");
		for (const r of checkAll()) {
			if (r.status === "behind") {
				const target = r.name === "pivoice" ? "--voice" : "--all";
				proposals.push({
					setting: `(release: ${r.name})`,
					from: r.local,
					to: r.remote,
					rationale: `New ${r.name} version available. Apply (gated): apple-pi update ${target} --yes`,
					severity: "info",
					source: "release",
				});
			}
		}
	} catch { /* offline / update-check unavailable — skip silently */ }

	const weekStart = weekDates[0], weekEnd = weekDates[6];
	const summary = `${proposals.length} proposal(s): ${proposals.map((p) => `${p.setting}[${p.severity}]`).join(", ") || "none"} | bash ${curr.bashPct}%/read ${curr.readPct}% | ${curr.turns} turns | ${curr.errors} errs`;
	console.log(`aggregate-week ${weekStart}..${weekEnd}: ${summary}`);

	const brief = renderBrief({ weekStart, weekEnd, curr, prev, proposals });
	if (args.dry) {
		console.log("\n" + brief);
		db.close(); return;
	}

	const proposalsDir = `${piDir()}/agent/proposals`;
	mkdirSync(proposalsDir, { recursive: true });
	const briefPath = `${proposalsDir}/${weekEnd}.md`;
	writeFileSync(briefPath, brief);
	console.log(`  brief → ${briefPath}`);

	db.close();
	const dbw = open("rw");
	// supersede any still-pending older proposals so only the latest is actionable.
	dbw.prepare(`UPDATE proposals SET status='superseded' WHERE status='proposed'`).run();
	dbw.prepare(
		`INSERT INTO proposals (created_at, week_start, week_end, brief_path, summary, changes_json, status)
		 VALUES (?,?,?,?,?,?, 'proposed')`,
	).run(isoNow(), weekStart, weekEnd, briefPath, summary, JSON.stringify(proposals));
	dbw.close();
	console.log(`  proposal row inserted (status='proposed'). Review with: apple-pi review`);
}

main();
