// sync/lib/gitignore.js — generate the default-deny .gitignore from a
// classification. Pure: classification in, string out.
//
// Strategy (proven on the hand-built config repo): ignore everything (`*`),
// re-allow directory traversal (`!*/`), then `!`-allow each portable +
// deviceLocal path (with all ancestor dirs for traversal). Secrets + deviceOnly
// are already blocked by `*`; we list them again at the bottom as explicit
// intent documentation and a belt-and-suspenders against a future loose allow.
//
// Card S-2. See .docs/decisions/2026-06-28-config-sync-feature.md.

"use strict";

/** Return every ancestor dir of a relative glob, plus the glob itself,
 *  as gitignore `!`-allow lines. Ensures git descends into each ancestor. */
function allowLines(glob) {
	const segs = glob.split("/");
	const lines = [];
	// ancestor dirs (traversal) — every prefix that ends at a `/`.
	let acc = "";
	for (let i = 0; i < segs.length - 1; i++) {
		acc += (i ? "/" : "") + segs[i];
		lines.push("!/" + acc + "/");
	}
	lines.push("!/" + glob);
	return lines;
}

/** Render a secret/deviceOnly glob as a plain ignore line (no `!`). */
function ignoreLine(glob) {
	// `sessions/**` → `/sessions/` (dir ignore is enough and clearer)
	if (glob.endsWith("/**")) return "/" + glob.slice(0, -3) + "/";
	return "/" + glob;
}

/** Generate the full .gitignore contents for a classification `c`
 *  (the object returned by paths.classify()).
 *  @param {object} c — classification
 *  @param {string[]} [extra] — extra rel paths to allow (README.md, etc.) */
function generate(c, extra = []) {
	const out = [];
	out.push("# Generated by `apple-pi sync`. DO NOT edit by hand — re-run");
	out.push("# `apple-pi sync init` (or `doctor --fix`) to regenerate.");
	out.push("#");
	out.push("# DEFAULT-DENY: everything is ignored. Only the portable methodology");
	out.push("# layer + the device-local config snapshot are allowlisted. Secrets");
	out.push("# (auth.json, the vault, sessions, browser-profile) are NEVER tracked.");
	out.push("");
	out.push("# --- ignore everything ---");
	out.push("*");
	out.push("");
	out.push("# --- re-allow directory traversal ---");
	out.push("!*/");
	out.push("");

	const seen = new Set();
	const push = (ln) => { if (!seen.has(ln)) { seen.add(ln); out.push(ln); } };

	out.push("# --- repo meta (always tracked) ---");
	push("!/.gitignore");
	for (const p of extra) {
		if (typeof p === "string" && p) allowLines(p).forEach(push);
	}
	out.push("");

	out.push("# --- portable (syncs; merges across devices) ---");
	for (const p of c.portable) allowLines(p).forEach(push);
	out.push("");
	out.push("# --- device-local (committed; reconcile per-device, don't overwrite) ---");
	for (const p of c.deviceLocal) allowLines(p).forEach(push);
	out.push("");

	out.push("# --- generated / regenerable (re-excluded even inside allowed trees) ---");
	out.push("/**/node_modules/");
	out.push("/**/dist/");
	out.push("/**/playwright-browsers/");
	out.push("**/*.log");
	out.push("**/.DS_Store");
	out.push("**/*.bak");
	out.push("**/*.bak.*");
	out.push("");

	out.push("# --- secrets + device-only (already blocked by `*`; listed for intent) ---");
	for (const p of c.secret) push(ignoreLine(p));
	for (const p of c.deviceOnly) push(ignoreLine(p));
	out.push("");

	return out.join("\n");
}

module.exports = { generate, allowLines, ignoreLine };
